-- Generated by sheetsToNeonSql.js
-- 2026-04-01T14:12:17.608Z
--
-- Drag-drop this file into Neon SQL Editor to bulk import questions.
-- Ensure table exists and subject_id is TEXT (see neon-custom-questions-subject-id-text.sql).

BEGIN;

-- Row 3 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'A function that has a range of [6, 12] is', '[]', '["f : R → R, f(x) = 6 + 3cos(9x)","f : R → R, f(x) = 6 + 6cos(3x)","f : R → R, f(x) = 9 - 3cos(6x)","f : R → R, f(x) = 9 - 6cos(3x)"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 4 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'All asymptotes of the graph of y = 2tan(π(x + 1/2)) are given by', '[]', '["x = k, k ∈ Z","x = 2k, k ∈ Z","x = 2k + 1, k ∈ Z","x = (4k + 1)/2, k ∈ Z"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 5 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'Which one of the following options best represents the graph of y = f(-x) + 2?', '[]', '["A","B","C","D"]', 'B', NULL, 'Original graph shown in exam image.', NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 6 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'Consider the system of equations below containing the parameter k, where k ∈ R: kx + 3y = k^2 and 2x + (2k + 1)y = 6 - 2k. Find the value(s) of k for which this system has no real solutions.', '[]', '["k = -2 only","k = 3/2 only","k = -2 or 3/2","k ∈ R \\ {-2, 3/2}"]', 'A', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 7 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'Which of the following sets represents a function that has an inverse function?', '[]', '["{(1, 3), (2, 0), (2, 1)}","{(-1, 3), (2, 2), (3, 1)}","{(-1, 3), (0, 1), (1, 3)}","{(1, 0), (2, 3), (1, 3)}"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 8 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'The trapezium rule is used, with two trapeziums, to estimate the area bounded by the graph of y = f(x), the x-axis and the lines x = 0 and x = 1. For which function will the trapezium rule estimate be larger than the exact area?', '[]', '["f(x) = 3 - e^x","f(x) = x^3 + 1","f(x) = 3sin(x) + 1","f(x) = log_e(x + 3)"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 9 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'Consider the algorithm below: n ← 17; k ← 5; while n > k, n ← n - k, print n, end while. In order, the values printed by the algorithm are', '[]', '["12","12, 7","12, 7, 2","12, 7, 2, -3"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 10 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'A random sample of n Victorian households is taken to estimate the proportion of all Victorian households that have vegetable gardens. The approximate 95% confidence interval calculated using this sample is (0.248, 0.552), correct to three decimal places. The number of households, n, in the sample is', '[]', '["10","28","40","49"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 11 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'One day, at a particular school, m students walked to school and the remaining n students travelled to school using a different form of transport. Of the m students who walked, 20% took at least 30 minutes to get to school. Of the n students who used a different form of transport, 40% took at least 30 minutes to get to school. Given that a randomly selected student took at least 30 minutes to get to school, the probability that they walked to school is given by', '[]', '["m/(m + 2n)","2n/(m + 2n)","m/(5(m + n))","1/3"]', 'A', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 12 (methods): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('methods', 'mcq', 'Section A', 'Consider f : R → R, f(x) = 2x^2 + x - 1 and g : R → R, g(x) = sin(x). The inequality (f ∘ g)(x) > 0 is satisfied when', '[]', '["sin(x) ≤ -1","-1 < sin(x) < 0","1/2 < sin(x) ≤ 1","0 < sin(x) < 1/2"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.609Z');

-- Row 13 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'type', 'topic', 'question', 'image_urls_json', 'options_json', 'answer', 'accepted_answers_json', 'guidance', 'passage', 2, '2026-04-01T14:12:17.609Z');

-- Row 14 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The median bag size bought by customers on the day was', '[]', '["2","3","3.5","4"]', 'B', NULL, NULL, 'At a fruit shop, customers can buy avocados in bags. The bag size ranges from one to six avocados per bag. The histogram shows the number of customers who bought each bag size on a particular day.', 1, '2026-04-01T14:12:17.609Z');

-- Row 15 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The total number of avocados sold in bags was', '[]', '["39","134","136","138"]', 'C', NULL, NULL, 'At a fruit shop, customers can buy avocados in bags. The bag size ranges from one to six avocados per bag. The histogram shows the number of customers who bought each bag size on a particular day.', 1, '2026-04-01T14:12:17.609Z');

-- Row 16 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The boxplots show the life expectancy, in years, for a sample of countries from two different continents (Sample H and Sample T). Which one of the following statements is correct?', '[]', '["The interquartile range for Sample T is greater than the interquartile range for Sample H.","The median for Sample T is more than 10 years greater than the median for Sample H.","The third quartile for Sample H is greater than the first quartile for Sample T.","Life expectancy in all Sample T countries exceeds the median life expectancy in Sample H."]', 'D', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 17 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The Association of Southeast Asian Nations (ASEAN) has 10 member nations. In which labelled column does the value of log10(population density) for Singapore lie?', '[]', '["A","B","C","D"]', 'D', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 18 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The heights of females aged between 16 and 18 years within a population are normally distributed. Using the 68–95–99.7% rule, the mean and standard deviation of the heights are respectively', '[]', '["150.5 and 21.3","154.9 and 7.1","164.7 and 7.1","171.8 and 14.2"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 19 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The first quartile is 74.9 years, the third quartile is 78.5 years, and the lowest five values are 68.5, 68.6, 69.0, 70.1 and 74.8 years. How many outliers would be displayed at the lower end of a boxplot?', '[]', '["1","2","3","4"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 20 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'From this table, the percentage of female car buyers whose preferred car colour is silver is closest to', '[]', '["33%","40%","42%","57%"]', 'B', NULL, NULL, 'The table shows the preferred car colour for a sample of female and male car buyers. Female: Black 28, Silver 42, White 35. Male: Black 55, Silver 32, White 42.', 1, '2026-04-01T14:12:17.610Z');

-- Row 21 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'Which one of the following is the most appropriate way to graphically display the data shown in the table above?', '[]', '["a histogram","a back-to-back stem plot","parallel boxplots","a segmented bar chart"]', 'D', NULL, NULL, 'The table shows the preferred car colour for a sample of female and male car buyers. Female: Black 28, Silver 42, White 35. Male: Black 55, Silver 32, White 42.', 1, '2026-04-01T14:12:17.610Z');

-- Row 22 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'In the scatterplot of games won against goals against for 12 Australian A-League men’s teams, the equation for the least squares line is closest to', '[]', '["games won = 16.8 - 0.178 × goals against","games won = 14.3 - 0.193 × goals against","games won = 12.5 - 0.165 × goals against","games won = 17.4 + 0.173 × goals against"]', 'A', NULL, NULL, 'In the scatterplot, the games won are plotted against the goals against for each of the 12 Australian A-League men’s teams after 27 games of the 2022–2023 season. A least squares line has been fitted to the data.', 1, '2026-04-01T14:12:17.610Z');

-- Row 23 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The correlation coefficient between games won and goals against is r = -0.466. Based on the correlation coefficient, it can be concluded that', '[]', '["fewer goals scored against is associated with a smaller number of wins.","fewer goals scored against causes a smaller number of wins.","more goals scored against causes a smaller number of wins.","more goals scored against is associated with a smaller number of wins."]', 'D', NULL, NULL, 'In the scatterplot, the games won are plotted against the goals against for each of the 12 Australian A-League men’s teams after 27 games of the 2022–2023 season. A least squares line has been fitted to the data.', 1, '2026-04-01T14:12:17.610Z');

-- Row 24 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'A logarithmic (base 10) transformation was applied to the variable life. With log10(life) as the response variable, the equation of the least squares line fitted to the transformed data is closest to', '[]', '["log10(life) = 1.57 + 0.0123 × doctors","log10(life) = 1.63 + 0.0326 × doctors","log10(life) = 1.79 + 0.0383 × doctors","log10(life) = 1.85 + 0.0403 × doctors"]', 'C', NULL, NULL, 'The table shows the life expectancy in years, life, and the number of doctors per 1000 people, doctors, for a sample of 10 countries in 2024. A scatterplot displaying the data is also shown.', 1, '2026-04-01T14:12:17.610Z');

-- Row 25 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'A squared transformation was applied to the variable doctors. The equation of the least squares line fitted to this transformed data is of the form life = a + b × (doctors)^2. Using this equation, the predicted life, in years, for a country with two doctors per 1000 people is closest to', '[]', '["73.6","74.0","74.5","74.9"]', 'C', NULL, NULL, 'The table shows the life expectancy in years, life, and the number of doctors per 1000 people, doctors, for a sample of 10 countries in 2024. A scatterplot displaying the data is also shown.', 1, '2026-04-01T14:12:17.610Z');

-- Row 26 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The time series graph is smoothed using five-median smoothing. The smoothed value for the margin in week 8, in points, is', '[]', '["32","35","38","41"]', 'C', NULL, NULL, 'The time series graph shows the margin, in points, for a team winning all of its games in the first 18 weeks of a season. The team plays one game per week.', 1, '2026-04-01T14:12:17.610Z');

-- Row 27 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'Which one of the following options best describes the qualitative features of the time series graph above?', '[]', '["decreasing trend only","irregular fluctuations only","structural change only","decreasing trend with irregular fluctuations"]', 'D', NULL, NULL, 'The time series graph shows the margin, in points, for a team winning all of its games in the first 18 weeks of a season. The team plays one game per week.', 1, '2026-04-01T14:12:17.610Z');

-- Row 28 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The number of drinks sold daily by a juice bar over a 10-day period is shown in the table. The four-mean smoothed number of drinks, with centring, sold on day 8 is closest to', '[]', '["134.25","140.0","142.75","145.75"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 29 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Data analysis', 'The seasonal index for the number of meat pie sales in winter is 1.75. To correct for seasonality, the actual number of meat pie sales for winter should be reduced, to the nearest whole percentage, by', '[]', '["25%","43%","57%","75%"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 30 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Recursion and financial modelling', 'Dani invests $4000 for three years. The account earns simple interest at 4% per annum. The balance in the account after three years can be calculated using', '[]', '["4000 × 1.04^3","3(1.04 × 4000)","4000 + (0.04 × 4000)^3","4000 + 3(0.04 × 4000)"]', 'D', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 31 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Recursion and financial modelling', 'A recurrence relation is of the form u0 = a, un+1 = Run + d. If a > 0, R = 0.5 and d = 0, the sequence generated will be', '[]', '["arithmetic and increasing","arithmetic and decreasing","geometric and increasing","geometric and decreasing"]', 'D', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 32 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Recursion and financial modelling', 'The table compares the value of an asset at various times using the flat rate and reducing balance methods of depreciation. After how many years will the value using flat rate depreciation first be lower than the value using reducing balance depreciation?', '[]', '["5","6","7","8"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 33 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Recursion and financial modelling', 'Steve owns gardening equipment that had an initial value of $12000. He will use the unit cost method to depreciate the value of this equipment per hour used. Steve uses the gardening equipment for 960 hours per year. The value of the gardening equipment is $7680 after two years. By what amount does the gardening equipment depreciate per hour used?', '[]', '["$2.25","$4.00","$4.17","$4.50"]', 'A', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 34 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Recursion and financial modelling', 'Donald invests $250000 into a perpetuity at an interest rate of 5% per annum. Donald receives a payment at the end of each year. When will the sum of all annual payments to Donald first exceed $250000?', '[]', '["at the end of year 13","at the end of year 17","at the end of year 21","at the end of year 25"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 35 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Recursion and financial modelling', 'Rita opens a savings account with an initial deposit of $4000. The account earns interest compounding weekly. After the interest is added each week, Rita deposits an additional $50 into the account. Assume there are exactly 52 weeks in one year. The annual interest rate, compounding weekly, that is required to achieve a balance of $14000 after three years is closest to', '[]', '["8.4%","14.2%","14.6%","17.2%"]', 'A', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 36 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Recursion and financial modelling', 'Virat invested $5000 into an account that earned interest compounding fortnightly. The effective annual interest rate for Virat’s investment was 4.51%. Assume that there are exactly 26 fortnights in one year. After five years, the amount of interest earned by Virat was closest to', '[]', '["$1128","$1234","$1262","$1264"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 37 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Recursion and financial modelling', 'Dennis invests $800000 in an annuity. The annuity earns interest at 4.8% per annum, compounding monthly. After the interest is credited to the annuity, Dennis receives a monthly payment of $6000. After some years, the balance of the annuity is $521118.96. For the remainder of the annuity, Dennis receives a monthly payment of $4767.66. The total number of years for which Dennis receives payments is closest to', '[]', '["19","20","21","22"]', 'A', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 38 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Matrices', 'Consider the matrix G where G = [[0,1,0],[1,0,1],[0,0,0]]. Which one of the following correctly describes matrix G?', '[]', '["a binary matrix","a permutation matrix","an identity matrix","a diagonal matrix"]', 'A', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 39 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Matrices', 'Consider the matrices A = [[2,0],[1,6]], B = [[3],[5]] and C = AB. The calculation that correctly determines element c21 is', '[]', '["2 × 3 + 0 × 5","2 × 5 + 3 × 0","1 × 3 + 6 × 5","1 × 5 + 6 × 3"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 40 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Matrices', 'Consider the matrix E = [[m,-9],[4,n]]. For the inverse of E to exist, the values of m and n, respectively, cannot be', '[]', '["3 and 12","12 and 3","3 and -12","-3 and -12"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 41 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Matrices', 'At a fast-food restaurant, team members use headsets to communicate. There are six different headsets: A, B, C, D, E and F. These headsets work on different frequencies, which means some staff members cannot directly communicate with each other. The matrix shows which headsets can directly communicate with each other. Which one of the following sequences allows a message to be communicated from headset A to headset E?', '[]', '["A - C - E","A - D - B - E","A - B - D - E","A - F - D - E"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 42 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Matrices', 'The female population of an animal species has been divided into four age groups (1, 2, 3 and 4), with age group 1 being the youngest. The age groups, birth rates and survival rates are presented in the life-cycle diagram. Which one of the following is a Leslie matrix that corresponds with this life-cycle diagram?', '[]', '["A","B","C","D"]', 'A', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 43 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Matrices', 'F is a 4 × 4 matrix. The element in row i and column j of F is f_ij. The elements are determined by the rule f_ij = i^2 - j. How many of the elements in F will be negative?', '[]', '["2","3","5","16"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 44 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Matrices', 'Consider the following four matrices A, B, C and D. Which one of the following computations is defined?', '[]', '["D(A + B)","C^T BD","C + BD","(DA)^T + D"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 45 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Matrices', 'Kyle (K), Lian (L), Maggie (M), Neil (N) and Ophelia (O) took part in a round-robin chess tournament in which each person played each of the others once. In each game there was a winner and a loser. The winner of the tournament was determined by T = D + D^2, where D and D^2 are, respectively, the one-step and two-step dominance matrices. Some of the individual match results were not recorded. An incomplete matrix D is shown. It is known that Maggie and Ophelia each won three of their four games, Kyle won two of his four games, Lian and Neil each won one of their four games, and Kyle defeated Neil. Which one of the following is matrix T?', '[]', '["A","B","C","D"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 46 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Networks and decision mathematics', 'Consider the graph shown. The number of Hamiltonian cycles in this graph, starting from E, is', '[]', '["0","2","4","6"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 47 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Networks and decision mathematics', 'Consider the graph shown. The number of bridges in this graph is', '[]', '["1","2","3","4"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 48 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Networks and decision mathematics', 'Consider the following weighted graph. The minimum spanning tree for this graph contains the edge with weight w. The length of this minimum spanning tree is', '[]', '["37 + w","44 + w","48 + w","49 + w"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 49 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Networks and decision mathematics', 'The network below shows the flow of water, in litres per minute, in a system of pipes connecting the source to the sink. What is the capacity of Cut 1?', '[]', '["27","31","33","37"]', 'C', NULL, NULL, 'The network below shows the flow of water, in litres per minute, in a system of pipes connecting the source to the sink.', 1, '2026-04-01T14:12:17.610Z');

-- Row 50 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Networks and decision mathematics', 'The network below shows the flow of water, in litres per minute, in a system of pipes connecting the source to the sink. What is the maximum flow of water, in litres per minute, from source to sink?', '[]', '["16","17","26","30"]', 'B', NULL, NULL, 'The network below shows the flow of water, in litres per minute, in a system of pipes connecting the source to the sink.', 1, '2026-04-01T14:12:17.610Z');

-- Row 51 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Networks and decision mathematics', 'The diagram below shows the network of roads that Sofia can use to travel between home and school. The numbers on the roads show the length, in metres, of each section of road. Using this network of roads, the shortest distance that Sofia can take to travel from home to school, in metres, is', '[]', '["3700","3800","3900","5100"]', 'A', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 52 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Networks and decision mathematics', 'Four contractors, P, Q, R and S, have been hired to complete work at one of four sites. Each contractor will be allocated to a different site. The cost for each contractor to complete the works, in dollars ($), is shown in the table. Martha completes two steps of the Hungarian algorithm: first row reduction, then column reduction. Which one of the following tables correctly displays the results after these two steps are completed?', '[]', '["A","B","C","D"]', 'B', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

-- Row 53 (general-maths): INSERT
INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)
VALUES ('general-maths', 'mcq', 'Networks and decision mathematics', 'The precedence table shows the 12 activities required to complete a project. The duration in days and immediate predecessors are shown. The project is to be completed in minimum time. The float time, in days, of Activity B is', '[]', '["4","6","8","12"]', 'C', NULL, NULL, NULL, 1, '2026-04-01T14:12:17.610Z');

COMMIT;

-- Summary: inserted=51, upserted=0, deleted=0, skipped=1