"use strict";

/**
 * Generate a Postgres SQL file from Google Sheets questions.
 *
 * Why: Cloudflare Pages can't read your local service-account key file, so we
 * bulk import into Neon by generating SQL you can run in Neon SQL Editor.
 *
 * Env (same as googleSheetsSync.js):
 *   GOOGLE_SHEETS_SPREADSHEET_ID
 *   GOOGLE_SHEETS_TAB_NAME (e.g. "english,methods,general-maths")
 *   GOOGLE_SERVICE_ACCOUNT_FILE or GOOGLE_SERVICE_ACCOUNT_JSON
 *
 * Output:
 *   ./neon-import-custom-questions.sql
 */

const fs = require("fs");
const path = require("path");
const sheetsSync = require("./googleSheetsSync");

function nowIso() {
  return new Date().toISOString();
}

function cleanText(value, maxLength = 2000) {
  return String(value || "").replace(/\u0000/g, "").trim().slice(0, maxLength);
}

function canonicalSubjectId(raw) {
  const s = cleanText(raw, 80).toLowerCase().replace(/\s+/g, " ");
  const aliases = {
    "mathematical methods": "methods",
    "mathematical-methods": "methods",
    "math methods": "methods",
    mm: "methods",
    "general mathematics": "general-maths",
    "general maths": "general-maths",
    "general-mathematics": "general-maths",
    "further mathematics": "further-maths",
    "further maths": "further-maths",
    "specialist mathematics": "specialist-maths",
    "specialist maths": "specialist-maths",
  };
  return aliases[s] || s;
}

function fixJsonMaybe(s) {
  const str = String(s || "").trim();
  if (!str) return "";
  // Replace smart quotes
  let t = str
    .replace(/[\u201c\u201d\u201e]/g, '"')
    .replace(/[\u2018\u2019]/g, "'");
  // Python-style ['a','b'] -> ["a","b"]
  if (/^\s*\[/.test(t) && /'/.test(t)) {
    t = t.replace(/'/g, '"');
  }
  return t;
}

function sqlStringLiteral(s) {
  // Standard single-quoted literal; escape single quotes.
  return `'${String(s).replace(/'/g, "''")}'`;
}

function sqlNullableText(s) {
  const t = String(s || "").trim();
  return t ? sqlStringLiteral(t) : "NULL";
}

function sqlNullableJsonText(s) {
  const t = fixJsonMaybe(s);
  return t ? sqlStringLiteral(t) : "NULL";
}

function isFiniteInt(n) {
  return Number.isFinite(n) && Math.floor(n) === n;
}

function buildUpsertByIdSql(p, id) {
  return [
    `INSERT INTO custom_questions (id, subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)`,
    `VALUES (${id}, ${sqlStringLiteral(p.subjectId)}, ${sqlStringLiteral(p.type)}, ${sqlStringLiteral(p.topic)}, ${sqlStringLiteral(p.question)}, ${sqlNullableJsonText(p.imageUrlsJson)}, ${sqlNullableJsonText(p.optionsJson)}, ${sqlNullableText(p.answer)}, ${sqlNullableJsonText(p.acceptedAnswersJson)}, ${sqlNullableText(p.guidance)}, ${sqlNullableText(p.passage)}, ${p.marks}, ${sqlStringLiteral(p.createdAt)})`,
    `ON CONFLICT (id) DO UPDATE SET`,
    `  subject_id = EXCLUDED.subject_id,`,
    `  type = EXCLUDED.type,`,
    `  topic = EXCLUDED.topic,`,
    `  question = EXCLUDED.question,`,
    `  image_urls = EXCLUDED.image_urls,`,
    `  options = EXCLUDED.options,`,
    `  answer = EXCLUDED.answer,`,
    `  accepted_answers = EXCLUDED.accepted_answers,`,
    `  guidance = EXCLUDED.guidance,`,
    `  passage = EXCLUDED.passage,`,
    `  marks = EXCLUDED.marks;`,
  ].join("\n");
}

function buildInsertSql(p) {
  return [
    `INSERT INTO custom_questions (subject_id, type, topic, question, image_urls, options, answer, accepted_answers, guidance, passage, marks, created_at)`,
    `VALUES (${sqlStringLiteral(p.subjectId)}, ${sqlStringLiteral(p.type)}, ${sqlStringLiteral(p.topic)}, ${sqlStringLiteral(p.question)}, ${sqlNullableJsonText(p.imageUrlsJson)}, ${sqlNullableJsonText(p.optionsJson)}, ${sqlNullableText(p.answer)}, ${sqlNullableJsonText(p.acceptedAnswersJson)}, ${sqlNullableText(p.guidance)}, ${sqlNullableText(p.passage)}, ${p.marks}, ${sqlStringLiteral(p.createdAt)});`,
  ].join("\n");
}

async function main() {
  if (!sheetsSync.isSheetsConfigured()) {
    console.error(
      "[sheetsToNeonSql] Sheets not configured. Set GOOGLE_SHEETS_SPREADSHEET_ID and GOOGLE_SERVICE_ACCOUNT_FILE/JSON.",
    );
    process.exit(1);
  }

  const outPath = path.join(__dirname, "neon-import-custom-questions.sql");
  const { rows, tabErrors } = await sheetsSync.readDataRows();
  if (tabErrors?.length) {
    console.warn(
      `[sheetsToNeonSql] Warning: ${tabErrors.length} tab(s) could not be read:`,
      tabErrors.map((t) => `${t.tabName}`).join(", "),
    );
  }

  let imported = 0;
  let updated = 0;
  let deleted = 0;
  let skipped = 0;

  const lines = [];
  lines.push("-- Generated by sheetsToNeonSql.js");
  lines.push(`-- ${nowIso()}`);
  lines.push("--");
  lines.push("-- Drag-drop this file into Neon SQL Editor to bulk import questions.");
  lines.push("-- Ensure table exists and subject_id is TEXT (see neon-custom-questions-subject-id-text.sql).");
  lines.push("");
  lines.push("BEGIN;");
  lines.push("");

  for (let i = 0; i < rows.length; i++) {
    const item = rows[i];
    const tabName = item.tabName;
    const p = sheetsSync.parseRow(item.row || []);
    if (sheetsSync.subjectIdFromTabMode() && tabName) {
      p.subject_id = tabName;
    }

    const action = String(p.action || "").trim().toUpperCase();
    const databaseId = p.database_id ? parseInt(p.database_id, 10) : NaN;

    if (action === "DELETE") {
      if (Number.isFinite(databaseId)) {
        lines.push(`-- Row ${i + 2} (${tabName || "tab"}): DELETE id=${databaseId}`);
        lines.push(`DELETE FROM custom_questions WHERE id = ${databaseId};`);
        lines.push("");
        deleted++;
      } else {
        skipped++;
      }
      continue;
    }

    const subjectId = canonicalSubjectId(cleanText(p.subject_id, 80));
    const type = cleanText(p.type, 30);
    const question = cleanText(p.question, 5000);
    if (!subjectId || !type || !question) {
      skipped++;
      continue;
    }

    const topic = cleanText(p.topic || "General", 200) || "General";
    const marks = Math.max(1, Math.round(Number(p.marks) || (type === "mcq" ? 1 : 2)));

    const payload = {
      subjectId,
      type,
      topic,
      question,
      optionsJson: p.options_json || "",
      answer: cleanText(p.answer || "", 2000),
      acceptedAnswersJson: p.accepted_answers_json || "",
      guidance: cleanText(p.guidance || "", 5000),
      passage: cleanText(p.passage || "", 20000),
      imageUrlsJson: p.image_urls_json || "",
      marks,
      createdAt: nowIso(),
    };

    if (Number.isFinite(databaseId)) {
      lines.push(`-- Row ${i + 2} (${tabName || "tab"}): UPSERT id=${databaseId}`);
      lines.push(buildUpsertByIdSql(payload, databaseId));
      lines.push("");
      updated++;
    } else {
      lines.push(`-- Row ${i + 2} (${tabName || "tab"}): INSERT`);
      lines.push(buildInsertSql(payload));
      lines.push("");
      imported++;
    }
  }

  lines.push("COMMIT;");
  lines.push("");
  lines.push(`-- Summary: inserted=${imported}, upserted=${updated}, deleted=${deleted}, skipped=${skipped}`);
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");

  console.log(`[sheetsToNeonSql] Wrote ${outPath}`);
  console.log(
    `[sheetsToNeonSql] Summary: inserted=${imported}, upserted=${updated}, deleted=${deleted}, skipped=${skipped}`,
  );
  if (tabErrors?.length) {
    console.log(`[sheetsToNeonSql] Tab errors: ${JSON.stringify(tabErrors, null, 2)}`);
  }
}

main().catch((e) => {
  console.error("[sheetsToNeonSql] Failed:", e?.message || e);
  process.exit(1);
});

