/**
 * Tricky short-answer practice bank (148 questions). Generated — edit in place if needed.
 * @see scripts/generate-maths-builtin-short.mjs
 */
import type { MethodsTopic } from "@/lib/methodsAreaTopic";
import type { Question, ShortQuestion } from "@/lib/subjects";

type Topic = MethodsTopic;

function short(
  topic: Topic,
  question: string,
  acceptedAnswers: string[],
  marks = 2,
): ShortQuestion {
  return { type: "short", topic, question, acceptedAnswers, marks };
}

const BANK: Question[] = [
  short("Functions and transformations", "If $f(x) = |2x - 6|$, find the minimum value of $f(x)$ on $\\mathbb{R}$.", ["0","0.0"], 2),
  short("Polynomial, power and rational functions", "Use the factor theorem: remainder when $P(x) = x^3 - 5x + 4$ is divided by $x-1$.", ["0","0.0"], 2),
  short("Circular functions", "Exact value: $\\sin\\!\\left(\\dfrac{\\pi}{6}\\right)$ (fraction).", ["1/2","0.5","0.50"], 2),
  short("Algebra and equations", "For $x^2 + kx + 16 = 0$ to have exactly one real solution, $|k| = $ ?", ["8","8.0"], 2),
  short("Differential calculus", "Differentiate $f(x) = x^6$. Coefficient of $x^5$ in $f'(x)$.", ["6","6.0"], 2),
  short("Applications of differentiation", "$f(x) = x^3 - 12x$ has stationary point at $x = 2$. Classify it: max or min? (one word)", ["min","minimum","local minimum"], 2),
  short("Integral calculus", "Antiderivative of $6x^2$ (no constant): coefficient of $x^3$.", ["2","2.0"], 2),
  short("Applications of integration", "Area between $y = x$ and $y = x^2$ on $[0,1]$ is $\\dfrac{1}{k}$. Find $k$.", ["6","6.0"], 2),
  short("Discrete random variables", "$X \\in \\{0,1\\}$ with $P(X=0)=0.7$, $P(X=1)=0.3$. Find $E(X)$.", ["0.3","0.30",".3"], 2),
  short("Continuous random variables", "PDF $f(x) = \\dfrac{1}{4}$ on $[2,6]$. Find $P(2 < X < 5)$.", ["0.75",".75","3/4"], 2),
  short("The normal distribution", "$X \\sim N(50, 10^2)$. Find $z$ for $x = 60$.", ["1","1.0"], 2),
  short("Sampling and sample proportions", "In a sample, $18$ successes in $80$ trials. Find $\\hat{p}$ (3 d.p.).", ["0.225",".225"], 2),
  short("Functions and transformations", "The graph of $y = f(x)$ is shifted **right** $4$ units. Write the rule.", ["f(x-4)","y=f(x-4)"], 2),
  short("Polynomial, power and rational functions", "For $P(x) = (x-2)^2(x+1)$, how many **distinct** real zeros?", ["2","2.0"], 2),
  short("Circular functions", "Exact value: $\\cos\\!\\left(\\dfrac{2\\pi}{3}\\right)$ (fraction).", ["-1/2","-0.5","-.5"], 2),
  short("Differential calculus", "Find $\\dfrac{d}{dx}(e^{4x})$ at $x = 0$.", ["4","4.0"], 2),
  short("Applications of differentiation", "Rectangle with perimeter $24$ cm. Side length (cm) for maximum area?", ["6","6.0"], 2),
  short("Applications of integration", "For $v(t) = 4t$, find the displacement from $t = 0$ to $t = 3$.", ["18","18.0"], 2),
  short("Discrete random variables", "$X \\sim \\operatorname{Bin}(10,0.2)$. Find $\\operatorname{Var}(X)$.", ["1.6","1.60"], 2),
  short("Continuous random variables", "Uniform on $[0,20]$. Median of $X$.", ["10","10.0"], 2),
  short("The normal distribution", "For standard normal $Z$, $P(Z < 0) = $ ?", ["0.5",".5","0.50"], 2),
  short("Sampling and sample proportions", "$\\hat{p} = 0.4$, $n = 100$. Standard error $\\sqrt{\\hat{p}(1-\\hat{p})/n}$ (3 d.p.).", ["0.049",".049","0.0490"], 2),
  short("Confidence intervals for proportions", "Margin of error $E = z\\times SE$. If $z=2$, $SE=0.03$, find $E$ (2 d.p.).", ["0.06",".06","0.060"], 2),
  short("Functions and transformations", "Find the domain of $f(x) = \\sqrt{7 - 2x}$ in interval notation: $(-\\infty, a]$. State $a$.", ["3.5","7/2","3.50"], 2),
  short("Polynomial, power and rational functions", "$y = \\dfrac{1}{x-3} + 2$ has vertical asymptote $x = $ ?", ["3","3.0"], 2),
  short("Exponential and logarithmic functions", "Simplify $\\ln(e^{7})$.", ["7","7.0"], 2),
  short("Circular functions", "Find the smallest positive solution to $\\sin x = \\frac{\\sqrt{2}}{2}$ on $[0,2\\pi)$. The answer is $\\frac{\\pi}{k}$. Find $k$.", ["4","4.0"], 2),
  short("Differential calculus", "Gradient of tangent to $y = x^3$ at $x = -2$.", ["12","12.0"], 2),
  short("Applications of differentiation", "Tangent slope is $\\dfrac{1}{3}$. Normal slope is?", ["-3","-3.0"], 2),
  short("Integral calculus", "Area under $y = 2x$ from $x = 0$ to $x = 4$.", ["16","16.0"], 2),
  short("Applications of integration", "A valid PDF on $[0,1]$ with $f(x) = k$ must have $k = $ ?", ["1","1.0"], 2),
  short("Discrete random variables", "Fair coin tossed $3$ times. $P(\\text{at least one head})$ as a fraction.", ["7/8","0.875",".875"], 2),
  short("Continuous random variables", "$\\displaystyle\\int_{-\\infty}^{\\infty} f(x)\\,dx$ for a PDF equals?", ["1","1.0"], 2),
  short("The normal distribution", "Empirical rule: about what percent of data lies within one standard deviation of the mean? (integer)", ["68","68%"], 2),
  short("Sampling and sample proportions", "A sample of only Year 12 students estimates school-wide opinion. One-word bias type?", ["bias","biased","selection"], 2),
  short("Confidence intervals for proportions", "Wider confidence interval mainly means more or less uncertainty? (one word)", ["more","greater"], 2),
  short("Functions and transformations", "Thermometer converts $F = \\dfrac{9C}{5}+32$. If $C = 20$, find $F$.", ["68","68.0"], 2),
  short("Polynomial, power and rational functions", "Profit model $P(x) = -(x-5)^2 + 9$ ($x$ in thousands). Maximum profit (units)?", ["9","9.0"], 2),
  short("Exponential and logarithmic functions", "Population $P(t)=1200(0.92)^t$. Percent decrease per time step? (integer)", ["8","8%"], 2),
  short("Circular functions", "Ferris wheel height $h(t)=10\\sin\\!\\left(\\dfrac{\\pi t}{6}\\right)+12$ (metres). Minimum height?", ["2","2.0"], 2),
  short("Algebra and equations", "Parameter $k$: solve $kx + 3 = 2x + 11$ for $x$ in terms of $k$. If $k \\neq 2$, $x = \\dfrac{8}{k-2}$. For **no** solution, $k$ equals?", ["2","2.0"], 2),
  short("Differential calculus", "Curve $y = x^2 e^{-x}$. At $x = 2$, is gradient positive or negative? (one word)", ["negative","Negative","neg"], 2),
  short("Applications of differentiation", "For $s(t) = t^3 - 6t$, find the velocity at $t = 2$.", ["6","6.0"], 2),
  short("Applications of integration", "Average value of $f(x) = 8$ on $[2,6]$ is?", ["8","8.0"], 2),
  short("Continuous random variables", "CDF $F(3) = 0.6$ means $P(X \\le 3) = $ ?", ["0.6",".6","0.60"], 2),
  short("The normal distribution", "$X \\sim N(100, 15^2)$. $P(X > 100)$ equals $P(Z > ?)$. Enter the $z$ threshold.", ["0","0.0"], 2),
  short("Sampling and sample proportions", "In $80$ trials there are $18$ successes. How many failures?", ["62","62.0"], 2),
  short("Confidence intervals for proportions", "If $\\hat{p}=0.5$, $n=400$, $z=1.96$, approximate $E$ (2 d.p.).", ["0.05",".05","0.049","0.0490"], 2),
  short("Functions and transformations", "Reflect $y=\\sqrt{x}$ in the $y$-axis then shift right 1. New domain in form $x \\leq k$. Find $k$.", ["-1","-1.0"], 2),
  short("Polynomial, power and rational functions", "$P(x)=(x-1)^2(x+2)$. Number of **distinct** $x$-intercepts?", ["2","2.0"], 2),
  short("Exponential and logarithmic functions", "Half-life: $N(t)=N_0(0.5)^{t/3}$. After $t=9$, fraction of $N_0$ remaining?", ["0.125",".125","1/8"], 2),
  short("Circular functions", "Tide model $d(t)=2.5\\cos\\!\\left(\\dfrac{\\pi t}{6}\\right)+4$. Amplitude (metres)?", ["2.5","2.50"], 2),
  short("Algebra and equations", "Inequality $|2x-1|<5$. Smallest **integer** solution?", ["-2","-2.0"], 2),
  short("Differential calculus", "$f(x)=\\ln(x^2+1)$. $f'(0)=$ ?", ["0","0.0"], 2),
  short("Applications of differentiation", "Fence 30 m against a wall (no fence on wall). Rectangle area $A = x(30-2x)$. Maximise: optimal $x$?", ["7.5","7.50","15/2"], 2),
  short("Applications of integration", "PDF $f(x)=\\dfrac{2x}{9}$ on $[0,3]$. Find $P(X<1.5)$.", ["0.25",".25","1/4"], 2),
  short("Discrete random variables", "You win \\$4 with probability $0.2$ and lose \\$1 otherwise. Expected profit per play?", ["0.2","0.20",".2"], 2),
  short("Continuous random variables", "Triangular PDF on $[0,2]$ with peak at $x=1$, height 1. Total area must be 1 — is this valid without scaling? yes or no.", ["no","No"], 2),
  short("The normal distribution", "Exam scores $N(70,100)$. Pass mark 60. $z$-score for 60?", ["-1","-1.0"], 2),
  short("Confidence intervals for proportions", "Poll $\\hat{p}=0.62$, $n=500$, 95% uses $z=1.96$. Approx margin of error (2 d.p.)", ["0.04",".04","0.042"], 2),
  short("Functions and transformations", "$f(x) = 2x + 1$. If $f(a) = 9$, find $a$.", ["4","4.0"], 2),
  short("Polynomial, power and rational functions", "$y = x^3 - x$. How many **distinct** real zeros?", ["3","3.0"], 2),
  short("Circular functions", "$\\tan\\!\\left(\\dfrac{\\pi}{4}\\right) = $ ?", ["1","1.0"], 2),
  short("Differential calculus", "$y = \\sin(3x)$. Find $\\dfrac{dy}{dx}$ at $x = 0$.", ["3","3.0"], 2),
  short("Applications of differentiation", "$f(x) = x^2 - 4x + 5$. $x$-coordinate of the stationary point?", ["2","2.0"], 2),
  short("Integral calculus", "$\\displaystyle\\int x^3\\,dx$ (no $+C$): coefficient of $x^4$ is $\\dfrac{1}{k}$. Find $k$.", ["4","4.0"], 2),
  short("Applications of integration", "Evaluate $\\displaystyle\\int_0^3 x^2\\,dx$.", ["9","9.0"], 2),
  short("Discrete random variables", "$P(X=0)=0.5$, $P(X=1)=0.5$. Find $\\operatorname{Var}(X)$.", ["0.25",".25","1/4"], 2),
  short("Continuous random variables", "PDF $f(x)=2x$ on $[0,1]$. Find $P(X < 0.5)$.", ["0.25",".25","1/4"], 2),
  short("The normal distribution", "$X \\sim N(0,1)$. $P(Z < 1) + P(Z > 1)$ equals?", ["1","1.0"], 2),
  short("Sampling and sample proportions", "Larger sample size $n$ makes $\\hat{p}$ typically more or less variable? (one word)", ["less","lower"], 2),
  short("Polynomial, power and rational functions", "$y = 2x^{-1}$. As $x \\to \\infty$, $y \\to$ ?", ["0","0.0"], 2),
  short("Exponential and logarithmic functions", "$\\log_{10}(1000) = $ ?", ["3","3.0"], 2),
  short("Circular functions", "Period of $y = \\sin(4x)$ is $\\dfrac{\\pi}{k}$. Find $k$.", ["2","2.0"], 2),
  short("Algebra and equations", "$x^2 - 5x + 6 = 0$. Smaller root?", ["2","2.0"], 2),
  short("Differential calculus", "Product rule: $f(x) = x^2 e^x$. Find $f'(0)$.", ["0","0.0"], 2),
  short("Applications of differentiation", "$f(x) = x^3 - 3x$. Find $f''(-1)$.", ["-6","-6.0"], 2),
  short("Integral calculus", "Evaluate $\\displaystyle\\int_0^1 e^x\\,dx$ (2 d.p.).", ["1.72","1.718","e-1","1.7183"], 2),
  short("Applications of integration", "Evaluate $\\displaystyle\\int_0^1 (3x + 2)\\,dx$.", ["3.5","3.50","7/2"], 2),
  short("Discrete random variables", "$X \\sim \\operatorname{Bin}(5, 0.4)$. Expected value $E(X)$?", ["2","2.0"], 2),
  short("Continuous random variables", "CDF at lower bound: $F(a) = $ ? for $X$ on $[a,b]$.", ["0","0.0"], 2),
  short("The normal distribution", "A $z$-score of $-2$ means the value is how many standard deviations below the mean? (integer)", ["2","2.0"], 2),
  short("Sampling and sample proportions", "$n=200$, $60$ successes. $\\hat{p}$ as decimal?", ["0.3",".3","0.30"], 2),
  short("Confidence intervals for proportions", "A 95% CI for $p$ refers to the long-run success rate of the ___ (one word).", ["method","methods","procedure"], 2),
  short("Functions and transformations", "$f(x)=5-x^2$. Maximum value of $f$?", ["5","5.0"], 2),
  short("Polynomial, power and rational functions", "$P(x)=x^3-8$. Real zero?", ["2","2.0"], 2),
  short("Exponential and logarithmic functions", "$3^x=\\dfrac{1}{9}$. $x=$ ?", ["-2","-2.0"], 2),
  short("Circular functions", "$\\cos(0)=$ ?", ["1","1.0"], 2),
  short("Algebra and equations", "$|x-3|=7$. Larger solution?", ["10","10.0"], 2),
  short("Differential calculus", "$f(x) = \\ln x$. Find $f'(e)$ (exact).", ["1/e","0.368","0.3679"], 2),
  short("Applications of integration", "A particle moves with $v(t) = 5$ m/s. Find the displacement from $t = 0$ to $t = 4$ s.", ["20","20.0"], 2),
  short("Discrete random variables", "$P(X\\geq 2)$ for $X\\in\\{0,1,2\\}$ with equal prob. Answer as fraction.", ["1/3","0.333","0.33"], 2),
  short("Continuous random variables", "PDF $f(x)=1$ on $[0,5]$. $P(X>4)$?", ["0.2",".2","1/5"], 2),
  short("The normal distribution", "Standard normal: $P(-1<Z<1)$ is about what percent (integer)?", ["68","68%"], 2),
  short("Sampling and sample proportions", "True population proportion is $p$. Sample proportion is $\\hat{p}$. Is $p$ usually known? yes or no.", ["no","No"], 2),
  short("Confidence intervals for proportions", "Same $\\hat{p}$ and $n$: 99% CI is wider than 95%? yes or no.", ["yes","Yes"], 2),
  short("Functions and transformations", "Given $f(x)=x+1$ and $g(x)=x^2$, find $(f\\circ g)(2)$.", ["5","5.0"], 2),
  short("Polynomial, power and rational functions", "Degree of $P(x)=5x^4-2x+7$?", ["4","4.0"], 2),
  short("Exponential and logarithmic functions", "$\\log_3(27)=$ ?", ["3","3.0"], 2),
  short("Circular functions", "$\\sin\\!\\left(\\dfrac{\\pi}{2}\\right)=$ ?", ["1","1.0"], 2),
  short("Algebra and equations", "$2^x=32$. $x=$ ?", ["5","5.0"], 2),
  short("Differential calculus", "$f(x) = x^4$. Find $f''(2)$.", ["48","48.0"], 2),
  short("Applications of differentiation", "Rectangle with perimeter $20$ cm. Maximum area (cm$^2$)?", ["25","25.0"], 2),
  short("Integral calculus", "Evaluate $\\displaystyle\\int_1^2 4x\\,dx$.", ["6","6.0"], 2),
  short("Applications of integration", "Area under $y = 6$ from $x = 1$ to $x = 5$.", ["24","24.0"], 2),
  short("Discrete random variables", "For $n=4$, $p=0.5$, find $P(X=2)$ as a fraction.", ["3/8","0.375",".375"], 2),
  short("Continuous random variables", "Median of uniform $[2,10]$?", ["6","6.0"], 2),
  short("The normal distribution", "$\\mu=40$, $\\sigma=5$. $z$ for $x=45$?", ["1","1.0"], 2),
  short("Sampling and sample proportions", "Simple random sample: every individual has equal chance of selection. True or false?", ["true","True","yes"], 2),
  short("Confidence intervals for proportions", "Point estimate for population proportion is $\\hat{p}$ or $p$? (symbol)", ["p hat","phat","p̂","hat p"], 2),
  short("Functions and transformations", "$y=|x|+1$. Minimum value?", ["1","1.0"], 2),
  short("Polynomial, power and rational functions", "$y=x^{-2}$. As $x \\to 0^+$, $y \\to$ ?", ["infinity","∞","inf"], 2),
  short("Exponential and logarithmic functions", "$e^0=$ ?", ["1","1.0"], 2),
  short("Circular functions", "$\\sin(\\pi)=$ ?", ["0","0.0"], 2),
  short("Algebra and equations", "$\\sqrt{x}=5$. $x=$ ?", ["25","25.0"], 2),
  short("Differential calculus", "$y = \\dfrac{1}{x}$. Gradient of tangent at $x = 2$.", ["-0.25","-1/4","-.25"], 2),
  short("Applications of differentiation", "Tangent to $y = x^2$ at $x = 3$. Gradient?", ["6","6.0"], 2),
  short("Integral calculus", "Antiderivative of $\\dfrac{1}{x}$ (no constant) uses $\\ln|x|$ plus which letter?", ["C","c"], 2),
  short("Discrete random variables", "$E(X)=\\sum x\\,P(X=x)$. If always $X=3$, then $E(X)=$ ?", ["3","3.0"], 2),
  short("Sampling and sample proportions", "$\\hat{p}=0.12$ from $n=50$. Number of successes?", ["6","6.0"], 2),
  short("Differential calculus", "$y = (3x - 1)^5$. Find $\\dfrac{dy}{dx}$ at $x = 1$.", ["240","240.0"], 2),
  short("Applications of integration", "$f(x) = x$ on $[0, 4]$. Average value of $f$ on this interval?", ["2","2.0"], 2),
  short("Differential calculus", "$f(x) = \\cos x$. Find $f'(\\pi)$.", ["0","0.0"], 2),
  short("Applications of integration", "PDF $f(x) = 0.25$ on $[0, 4]$. Find $P(1 < X < 3)$.", ["0.5",".5","1/2"], 2),
  short("Differential calculus", "$f(x) = e^{2x}$. Find $f'(1)$ in form $ke^2$. Integer $k$?", ["2","2.0"], 2),
  short("Applications of integration", "Area between $y = 2$ and $y = x$ on $[0, 2]$.", ["2","2.0"], 2),
];

export const METHODS_BUILTIN_QUESTIONS: Question[] = BANK;
